#!/usr/bin/env python3
"""Generate Cueola's semantic SF Symbol mask stylesheet."""

from __future__ import annotations

import argparse
import json
import os
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[1]
DEFAULT_MAP = REPO_ROOT / "design-system/apple/symbols/semantic-map.json"
DEFAULT_CATALOG = REPO_ROOT / "design-system/apple/symbols/catalog.json"
DEFAULT_OUTPUT = REPO_ROOT / "assets/sf-symbols.css"


def css_url(from_file: Path, target: Path) -> str:
    relative = os.path.relpath(target, from_file.parent).replace(os.sep, "/")
    return relative.replace('"', '\\"')


def build_css(semantic_map: Path, catalog_path: Path, output: Path) -> str:
    mapping = json.loads(semantic_map.read_text(encoding="utf-8"))["symbols"]
    catalog = json.loads(catalog_path.read_text(encoding="utf-8"))
    symbols = {item["name"]: item for item in catalog["symbols"]}

    missing = sorted({name for name in mapping.values() if name not in symbols})
    if missing:
        raise SystemExit("Missing catalog symbols: " + ", ".join(missing))

    lines = [
        "/* Generated by scripts/build_sf_symbol_css.py. Do not edit directly. */",
        ".sf-symbol {",
        "  display: inline-block;",
        "  width: 1em;",
        "  height: 1em;",
        "  flex: 0 0 auto;",
        "  color: inherit;",
        "  background: currentColor;",
        "  -webkit-mask: var(--sf-symbol) center / contain no-repeat;",
        "  mask: var(--sf-symbol) center / contain no-repeat;",
        "  vertical-align: -0.125em;",
        "}",
        ".sf-symbol.symbol-lg { width: 1.3em; height: 1.3em; }",
        ".sf-symbol.symbol-sm { width: .86em; height: .86em; }",
        "",
    ]
    for semantic_name, symbol_name in mapping.items():
        runtime_path = REPO_ROOT / "design-system/apple/symbols" / symbols[symbol_name]["runtimePath"]
        lines.append(
            f'.sf-symbol[data-symbol="{semantic_name}"] '
            f'{{--sf-symbol:url("{css_url(output, runtime_path)}");}}'
        )
    lines.extend(
        [
            "",
            "@media (forced-colors: active) {",
            "  .sf-symbol { background: ButtonText; }",
            "}",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--semantic-map", type=Path, default=DEFAULT_MAP)
    parser.add_argument("--catalog", type=Path, default=DEFAULT_CATALOG)
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    args = parser.parse_args()

    output = args.output.resolve()
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(
        build_css(args.semantic_map.resolve(), args.catalog.resolve(), output),
        encoding="utf-8",
    )
    print(f"Wrote {output.relative_to(REPO_ROOT)}")


if __name__ == "__main__":
    main()
